spring:
  config.activate.on-profile: default
  web.resources.static-locations: file:./app/
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock.users:
      admin:
        password: admin
        roles:
          - admin
      alice:
        password: null
        roles:
          - support
